/**
 * OGSE — Open Geopolitical Simulation Engine
 * Core type definitions — fully dynamic for N actors and N conflicts
 */

// ============================================================================
// ENUMS
// ============================================================================

export type ConflictStatus = 'escalating' | 'de-escalating' | 'stable' | 'frozen' | 'stalemate' | 'active';
export type ConflictCategory = 'hybrid' | 'military' | 'economic' | 'proxy' | 'cyber' | 'diplomatic';
export type EventSignificance = 'critical' | 'high' | 'medium' | 'low';
export type EventCategory = 'military' | 'diplomatic' | 'economic' | 'political';
export type ConfidenceLevel = 'high' | 'medium' | 'low';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type ActorRole = 'primary' | 'secondary' | 'proxy' | 'mediator';
export type CausalNodeCategory = 'actor' | 'event' | 'effect' | 'variable';
export type CausalEdgeStrength = 'strong' | 'moderate' | 'weak';
export type TrendDirection = 'up' | 'down' | 'stable' | 'increasing' | 'decreasing';

// ============================================================================
// CORE ENTITY INTERFACES
// ============================================================================

export interface Source {
  name: string;
  url?: string;
}

export interface ConflictActor {
  name: string;
  role: ActorRole;
  country_code: string;
  flag: string;
  interests: string[];
  red_lines: string[];
}

// ============================================================================
// SUPABASE TABLE ROWS
// ============================================================================

export interface Conflict {
  id: string;
  name: string;
  category: ConflictCategory;
  status: ConflictStatus;
  intensity: number;
  summary: string | null;
  tags: string[] | null;
  actors: ConflictActor[];
  start_date: string | null;
  created_at: string | null;
}

export interface TimelineEvent {
  id: string;
  conflict_id: string | null;
  title: string;
  description: string;
  date: string;
  category: EventCategory;
  significance: EventSignificance;
  sources: Source[] | null;
  created_at: string | null;
}

// ============================================================================
// AI-GENERATED ANALYSIS — FULLY DYNAMIC
// ============================================================================

/** Military posture for any actor */
export interface MilitaryPosture {
  current_posture: string;
  recent_actions: string[];
  stated_objectives?: string[];
  deployments?: string[];
  readiness_level?: string;
}

export interface EconomicMeasures {
  active_sanctions: string[];
  trade_impact: string;
  currency_effects: string;
  energy_sector_impact?: string;
}

export interface DiplomaticChannel {
  name: string;
  status: 'active' | 'cold' | 'suspended' | 'broken' | 'unknown';
  last_contact?: string;
}

export interface DiplomaticStatus {
  current_tone: string;
  active_channels: (DiplomaticChannel | string)[];
  third_party_mediators: string[];
  negotiation_status?: string;
}

export interface InternalPressure {
  pressure_level: number;
  political_pressure?: string;
  regime_stability?: string;
  economic_grievances?: string[];
  public_sentiment?: string;
}

/** Briefing — dynamic: military_posture and internal_pressure are keyed by actor slug */
export interface Briefing {
  summary: string;
  confidence_level: ConfidenceLevel;
  confidence_reasoning?: string;
  military_posture: Record<string, MilitaryPosture>;
  economic_measures: EconomicMeasures;
  diplomatic_status: DiplomaticStatus;
  internal_pressure: Record<string, InternalPressure>;
  key_developments?: string[];
  strategic_insights?: string[];
}

/** A single impact metric */
export interface ImpactMetric {
  score: number;
  trend: TrendDirection;
  confidence_low?: number;
  confidence_high?: number;
  drivers?: string[];
  primary_channels?: string[];
  mechanisms?: string[];
  stressed_alliances?: string[];
  affected_countries?: string[];
  oil_price_impact?: string;
  strait_of_hormuz_risk?: number;
  [key: string]: unknown;
}

/**
 * Impact assessment — fully dynamic.
 * Keys are generated by the LLM based on actors involved.
 * e.g. domestic_stability_usa, domestic_stability_iran, regional_destabilization, etc.
 */
export type ImpactAssessment = Record<string, ImpactMetric>;

export interface CausalNode {
  id: string;
  label: string;
  description: string;
  category: CausalNodeCategory;
}

export interface CausalEdge {
  id?: string;
  source: string;
  target: string;
  strength: CausalEdgeStrength;
  description?: string;
  relationship?: string;
}

export interface CausalGraph {
  nodes: CausalNode[];
  edges: CausalEdge[];
}

/** Dynamic pathway actions keyed by actor */
export interface PathwayActions {
  [actor: string]: string[] | undefined;
}

export interface PolicyPathway {
  id: string;
  name: string;
  description: string;
  risk_level: RiskLevel;
  probability_estimate: number;
  probability_confidence_low?: number;
  probability_confidence_high?: number;
  time_horizon?: string;
  required_actions?: PathwayActions;
  preconditions?: string[];
  obstacles?: string[];
  systemic_side_effects?: string[];
  expected_outcomes?: string[];
  warning_indicators?: string[];
}

export interface AnalysisSnapshot {
  id: string;
  conflict_id: string | null;
  triggered_by_event_id: string | null;
  briefing: Briefing | null;
  causal_graph: CausalGraph | null;
  pathways: PolicyPathway[] | null;
  impact: ImpactAssessment | null;
  is_latest: boolean | null;
  model_version: string | null;
  created_at: string | null;
}

// ============================================================================
// COMPONENT PROPS
// ============================================================================

export interface ConflictHeaderProps {
  conflict: Conflict;
  snapshot: AnalysisSnapshot | null;
  snapshotHistory: Pick<AnalysisSnapshot, 'id' | 'created_at' | 'triggered_by_event_id'>[];
  events: TimelineEvent[];
}

export interface BriefingPanelProps {
  snapshot: AnalysisSnapshot | null;
  actors?: ConflictActor[];
}

export interface ImpactMetricsProps {
  snapshot: AnalysisSnapshot | null;
  actors?: ConflictActor[];
}

export interface TimelineViewProps {
  events: TimelineEvent[];
}

export interface CausalGraphViewProps {
  snapshot: AnalysisSnapshot | null;
}

export interface PathwayExplorerProps {
  snapshot: AnalysisSnapshot | null;
}

// ============================================================================
// SEED DATA TYPES
// ============================================================================

export interface ConflictSeedData {
  name: string;
  category: ConflictCategory;
  status: ConflictStatus;
  intensity: number;
  start_date: string;
  summary: string;
  tags: string[];
  actors: ConflictActor[];
}

export interface TimelineEventSeedData {
  date: string;
  title: string;
  description: string;
  category: EventCategory;
  significance: EventSignificance;
  sources: Source[];
}

// ============================================================================
// CONSTANTS
// ============================================================================

export const CAUSAL_NODE_COLORS: Record<CausalNodeCategory, string> = {
  actor: '#e8c547',
  event: '#ff4444',
  effect: '#4488ff',
  variable: '#888899',
};

export const CAUSAL_NODE_RADIUS: Record<CausalNodeCategory, number> = {
  actor: 18,
  event: 12,
  effect: 10,
  variable: 8,
};

export const RISK_COLORS: Record<RiskLevel, string> = {
  low: 'text-og-green bg-[rgba(68,255,136,0.12)]',
  medium: 'text-accent-color bg-accent-dim',
  high: 'text-[hsl(30,100%,60%)] bg-[rgba(255,140,0,0.12)]',
  critical: 'text-red-vivid bg-red-dim',
};

export const EVENT_SIZE_MAP: Record<EventSignificance, number> = {
  critical: 16,
  high: 12,
  medium: 8,
  low: 6,
};

export const EVENT_COLOR_MAP: Record<EventCategory, string> = {
  military: 'hsl(var(--red-vivid))',
  diplomatic: 'hsl(var(--blue-vivid))',
  economic: 'hsl(var(--accent))',
  political: 'hsl(270,100%,63%)',
};

// ============================================================================
// UTILITY: derive a slug from actor name for keying
// ============================================================================

export function actorSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

/** Check if an impact metric key is a "domestic stability" metric (reversed scoring) */
export function isReversedMetric(key: string): boolean {
  return key.startsWith('domestic_stability');
}

/** Pretty-print a metric key */
export function metricLabel(key: string): string {
  return key.replace(/_/g, ' ').toUpperCase();
}
